name: CI

on:
  push:

jobs:
  build-and-test:

    name: Build and test emscripten

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - run: |
        docker run -di --rm --name emscripten emscripten/emsdk:3.1.49 bash
        docker cp ${{ github.workspace }}/. emscripten:/src
        docker exec emscripten emcc -v
        docker exec emscripten apt-get update
        docker exec emscripten apt-get install -y cmake flex bison libglpk-dev libgmp-dev libarpack2-dev python3-venv
        docker exec emscripten cp /src/tools/IGRAPH_VERSION /src/vendor/igraph
        docker exec emscripten mkdir build
        docker exec -w /src/build emscripten emcmake cmake .. -DCMAKE_BUILD_TYPE=Release
        docker exec -w /src/build emscripten make test VERBOSE=1

    - if: always()
      run: docker stop emscripten || true
